linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  depguard:
    list-type: blacklist
  misspell:
    locale: UK
  lll:
    line-length: 160
  goimports:
    local-prefixes: github.com/nick-jones/brulee
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental

linters:
  enable-all: true
  disable:
    - scopelint
    - unparam
    - goimports
    - maligned
    - prealloc
    - gosec
    - gochecknoglobals
